require 'banktools-br/banks/utilities'
require 'banktools-br/banks/itau'
require 'banktools-br/banks/bb'
require 'banktools-br/banks/caixa_economica'
require 'banktools-br/banks/santander'
require 'banktools-br/banks/banrisul'
